version: 2.1
orbs:
  python: circleci/python@volatile

jobs:
  build:
    executor: python/default
    resource_class: small
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Install PlatformIO
          command: pip install --upgrade platformio
      - run:
          name: Compile Project
          command: pio run
  lizard:
    executor: python/default
    resource_class: small
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Install lizard
          command: pip install --upgrade lizard
      - run:
          name: Check Project
          command: lizard src
  flawfinder:
    executor: python/default
    resource_class: small
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Install flawfinder
          command: pip install --upgrade flawfinder
      - run:
          name: Check Project
          command: flawfinder src

workflows:
  main:
    jobs:
      - lizard
      - flawfinder
      - build:
          requires:
            - lizard
            - flawfinder
